### PR TITLE
skip items with no url key

### PR DESCRIPTION
**Pull request by javiermon**
Hi

I've recently have been having trouble with items from fanarttv with wrong url key:
01:04:29 T:140367684941568  NOTICE: {u'url': u'http://assets.fanart.tv/fanart/movies/46705/movielogo/blue-valentine-4f76bcbf09e11.png', u'lang': u'en', u'id': u'1472', u'
likes': u'1'}
01:04:29 T:140367684941568  NOTICE: {u'url': u'http://assets.fanart.tv/fanart/movies/46705/hdmovielogo/blue-valentine-50f28de6397ac.png', u'lang': u'en', u'id': u'21496',
 u'likes': u'2'}
01:04:29 T:140367684941568  NOTICE: {u'lang': u'de', u'url': u'http://assets.fanart.tv/fanart/movies/46705/moviedisc/blue-valentine-501507983136f.png', u'disc': u'1', u'l
ikes': u'!', u'disc_type': u'dvd', u'id': u'7729'}
01:04:29 T:140367684941568  NOTICE: {u'url': u'http://assets.fanart.tv/fanart/movies/46705/hdmovieclearart/blue-valentine-50f28e0001ed5.png', u'lang': u'en', u'id': u'214
97', u'likes': u'1'}
01:04:29 T:140367684941568  NOTICE: {u'ubl': u'http://assets.fanart.tv/fanart/movies/46705/moviethumb/blue-valentine-51ce7f38bceb3.jpg', u'lang': u'en', u'id': u'40100', 
u'likes': u'1'}

This example triggers this exception:
01:04:29 T:140367684941568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: None object cannot be quoted
                                            Traceback (most recent call last):
                                              File "/home/javier/.xbmc/addons/script.artwork.downloader/default.py", line 823, in <module>
                                                Main()
                                              File "/home/javier/.xbmc/addons/script.artwork.downloader/default.py", line 140, in **init**
                                                self.download_artwork(mediaList, providers['movie_providers'])
                                              File "/home/javier/.xbmc/addons/script.artwork.downloader/default.py", line 358, in download_artwork
                                                temp_image_list = self.provider.get_image_list(currentmedia['id'])
                                              File "/home/javier/.xbmc/addons/script.artwork.downloader/lib/provider/fanarttv.py", line 153, in get_image_list
                                                image_list.append({'url': urllib.quote(item.get('url'), ':/'),
                                              File "/usr/lib64/python2.7/urllib.py", line 1269, in quote
                                                raise TypeError('None object cannot be quoted')
                                            TypeError: None object cannot be quoted
                                            -->End of Python script error report<--

The following changes should fix the issue.

Regards,

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
complain at fanart.tv as the url should ALWAYS be there.
they should fix it not me.

**Comment by MartijnKaijser** [comment]
nothing wrong with this movie:
http://xbmclogs.com/show.php?id=174907

all images have an URL. since you provide only a snippet of the log which in my eyes is useless. turn on debugging in xbmc and in the addon, add a log(item)  line in the place where you changed the code and try that movie again. also remove commoncache.db from the temp folder in userdata before trying.
and use pastebin or xbmclogs instead of pasting crap in tickets

**Comment by MartijnKaijser** [comment]
was it solved somehow?

**Comment by javiermon** [comment]
I've reported in fanart.tv. Will check after removing commoncache.db and see if it's happening again, but if you don't want to check if the parameter exists, there no point in this pull request. Sorry for the "crap" in the ticket.

**Comment by MartijnKaijser** [comment]
sorry for calling it crap but it's nearly impossible to follow when just dumped into a ticket/PR.
if i would need to check if it exists i should need to check every single parameter in there (and for all providers).
also i have never seen this in all those years

**Comment by javiermon** [comment]
Well, before looking into this, the traces with debug enabled didn't say much, so I had to print the item in the loop to see what was happening, hence the patch. 

I agree that checking for each parameter maybe a bit too much, but in this scenario the script completely dies, which you might agree is not very good from the user point of view: Launching artwork downloader from programs and the script fails at some point.

I personally think the best thing to do here would be to do this inside a try/except block so if the parsing fails at least the script can continue with the next item in the library, instead of completely failing because the web response is incorrectly formed.

Thanks.

**Comment by MartijnKaijser** [comment]
with a try..except you will never catch any bug/problem again.
even catching the except and printing in the log makes little sense as no user would ever report it since he doesn't know.
i might as well encapsulate the entire program with try except.
in the last 2 years this is the first time any one mentioned an error like this.
and only checking for the url makes no sense because when another one is missing it dies as well.
so i rather have the error and users giving the log than masking it

**Comment by javiermon** [comment]
I've seen other problems get logged, for example when permissions won't let write fanart in the movie folder and the script doesn't die, just logs the error and continue. Anyway, I understand your reasoning and I can live with patching the script when it fails.

**Comment by MartijnKaijser** [comment]
write permissions are very very common :)

**Pull request closed without merging**
