### PR TITLE
polish language update

### PR DESCRIPTION
**Pull request by cienislaw**
changed some texts to fit better (ClearArt etc in original), translated new strings

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
could you please rebase your version first before doing a PR.
That way we don't have the commits 'merge remote-tracking...'

**Comment by cienislaw** [comment]
how to do this? when i did git rebase now nothing changed. please advice how to solve that.

**Comment by MartijnKaijser** [comment]
http://book.git-scm.com/4_rebasing.html

If that doesn't work make a backup of your transalted file. Do a git reset on you tracking branch and just place the translated version back in. Push to your fork and do a PR commit update.

(takes some practise to get this working)

**Comment by MartijnKaijser** [comment]
Some more info http://help.github.com/  -> intermediate

Easy program for doing git operations -> SmartGit   http://www.syntevo.com/smartgit/index.html

**Comment by cienislaw** [comment]
thanx for tips but looks like i just messed more. i've reset repo 10 days back (before my changes), i've updated it to latest, but still in commit history i see those unwanted. i will try to commit my changes... and i've just added to more commits;-( 

how to clean up my commits history to discard all those i've did today?

**Comment by MartijnKaijser** [comment]
with reset you should reset your local version to latest commit. Then apply your changes. After that you should do a force push. this will overwrite all the commit on github page

**Comment by cienislaw** [comment]
thanx for help, i will read a bit about rebasing so i will not screw up again in future. also i will not do commit without PR - i have my translation in separate location (using OmegaT+ for the process) and just fire up script to generate latest translation and copy it to repo folder. thanx again for help and keep up good work.

**Pull request closed without merging**
