### PR TITLE
Prework on addon max downloads

### PR DESCRIPTION
**Pull request by MartijnKaijser**
Did some prework on the GUI for adding the maximum numbers of downloads per title.
Maximum downloads from 1 to 20
minimum rating 1 to 10

Let me now what you think of this and if ok i will merge to master.

EDIT:
here's a screenshot for easy reference
http://img15.imageshack.us/img15/9540/screenshot000zv.png

### CODE REVIEW

**Comment by paddycarey** [comment]
I think 20's a bit low, is it possible for the slider to jump in intervals? 5, 10, 15... 50 i think would work better
----- Original message -----

**Comment by MartijnKaijser** [comment]
Hmm let me see if that's possible. I'll have to check some other addons/wiki.
We can easily raise the number on how much we want en just let the user select.
One thing is that the solo mode must also follow this setting. So maybe look at an easy way of selecting what values to  include in solo/bulk for easy maintenance

**Comment by ghost** [comment]
If you look at the xbmc.lyrics script, it looks like the following line sets up an increment of 10...

&lt;setting label="30110" type="slider" id="fetch_lyrics_delay" default="100" range="100,10,500" format="%1.f $ADDON[script.xbmc.lyrics 30111]"/&gt;

Let me know if that works, or if that's just completely wrong

**Comment by MartijnKaijser** [comment]
doh, was it that easy :)
OK that works.
Min: 0 or 5? (one isn't an option or else you'll get 6, 11, ...)
Maximum: 50?
Increment: 5 or 10?

**Comment by ghost** [comment]
I'd say a minimum of 5, maximum of 50, increment of 5...keep it simple

**Comment by paddycarey** [comment]
that's exactly what i was thinking

we need to make sure it can be enabled/disabled of course in case anyone wants to download all the fanart

----- Original message -----

**Comment by ghost** [comment]
One comment: if you add **subsetting="true"** to the sub options, it will automatically add the hyphen before the option title

**Comment by MartijnKaijser** [comment]
thanks changed that. Only want to remove the .00 from the values
I tried: format="%1.f" (found in the lyrics script) but no luck.
Any idea what i did wrong?

**Comment by ghost** [comment]
Try **%.0f**

**Comment by MartijnKaijser** [comment]
format="%.0f" and still 15.00

**Comment by ghost** [comment]
Hmmm...%d?

**Pull request merged**
