### PR TITLE
season artwork support

### PR DESCRIPTION
**Pull request by paradix**
This is of course a first draft, so please have this in mind :)

after the changes made to JSON-RCP allowing to update season details I made some changes to the script that maybe useful until its possible to have the ListItem.SeasonId in the GUI.

It can be run with the command
XBMC.RunScript(script.artwork.downloader, mode=gui, mediatype=season, dbid=$INFO[ListItem.DBID], seasonno=$INFO[ListItem.Label]

It just needs the right condition, so it can be run from the DialogVideoInfo
For example a visible condition for a button:
<visible>Substring(ListItem.Label, $LOCALIZE[20373], left) + System.HasAddon(script.artwork.downloader)</visible>

Another thing: do the addon need to download the file locally? Can't only the remote url be added to the database? Of course not for extrafanart or extrathumbs, but this could be an option.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
sorry but i don't like the implementation and i'd rather do it myself

**Comment by paradix** [comment]
no need to be sorry :) it's just a workaround until xbmc offers the correct dbid for the season

**Comment by paradix** [comment]
maybe you could in at least two sentences say what you don't like?

**Comment by MartijnKaijser** [comment]
basically a lot of unneeded changes in the diff that make no sense. like here
https://github.com/XBMC-Addons/script.artwork.downloader/pull/80/files#diff-535306ae2b21e7a0f1318b2c8a63af5aR73

changing it to mediatype season which isn't correct and there's no support for mass downloading/updating, only through GUI. also you only did thumb and banner but there's no poster changes.

**Comment by paradix** [comment]
Is there any chance that you will add season support for the Gotham release? Maybe I could  help in any way? The code can be corrected or written from scratch :)

**Comment by MartijnKaijser** [comment]
already started 2e22b9137226a70da5dadae9f2fec91798b0330d

**Pull request closed without merging**
