### PR TITLE
German encoding/translation fix

### PR DESCRIPTION
**Pull request by tkurbad**
As @CutSickAss pointed out in pull request #72, the encoding of addons.xml is somehow messed up. For me, editing the file with a Linux editor actually replaced it as a whole during git commit, which points in the direction of it being DOS encoded.

Aside from the uglyness of having to replace the whole file, this PR provides the fix for the German entries along with slightly updated / beautified translations in strings.xml.

### CODE REVIEW

**Comment by CutSickAss** [comment]
Yeah, but you copy-pasted the entire file, overwriting my fix for the Greek text... You should have just edited the German text.

**Comment by tkurbad** [comment]
Sorry, but that's why we're on github. Someone just needs to merge our changes.

Also, as I pointed out earlier, I just edited the file with a Linux text editor, which alone lead to the replacement of every single line.
The problem is that the file pretends to be UTF-8, but it isn't. It's something else that I'm unable to figure out.

**Comment by tkurbad** [comment]
@CutSickAss, as you can see, I now incorporated your changes of addon.xml into mine. So, all you need to do is remove https://github.com/CutSickAss/script.artwork.downloader/commit/3012ce8b96e01aa3ad7e88a904da2ed3a9c9e4a8 from your PR, and everything will be fine. (Except the languages that still need to be fixed, of course... ;-)
At least this would mean no merge conflicts for the package maintainer.

And all other language contributors may then fix a file that's _really_ UTF-8 in the first place.

**Comment by CutSickAss** [comment]
OK, I deleted my PR with the addon.xml, and created a new one containing only the changes on the Greek strings.xml file. Thanks.

**Comment by MartijnKaijser** [comment]
A lot of unnecessary changes. Since I will use Transifex all this will be lost anyway

**Comment by tkurbad** [comment]
Sorry, I've had no info on your transition to Transifex.

**Comment by MartijnKaijser** [comment]
You couldn't have :) 
Just send request but was planning on it long time

**Pull request closed without merging**
