### PR TITLE
Add 'extrafanart' to Kodi database as 'fanart#'

### PR DESCRIPTION
**Pull request by rmrector**
An expansion on BigNoid's pull request, extra fanart is now added to the database alongside the regular 'fanart'/'poster'/'clearlogo'/etc art as 'fanart#'. Based on branch Frodo as that's the released version that's been available from Kodi for quite a while, and master development is fairly old and not directly mergeable with the released version. At this point I'd prefer to pick changes from master specifically and merge them into this branch.

It needs more eyes on it before it is merged in. I've made a [forum post](http://forum.kodi.tv/showthread.php?tid=236649) for discussion.

By default it still downloads extra fanart to the 'extrafanart' directory next to the media for skins using the classic extrafanart. It can be disabled with a setting "Copy extra fanart to folder".

When using local files it will still download them to the 'extrafanart' folder, but the URL in the DB will be to those local files, like other art.

Movie 'extrathumbs' are left as they are. Artwork Downloader only seems to be grabbing scaled-down fanart for these, and I'm not sure how useful that is.

It also includes a plugin path to stitch these fanarts together for 'multiimage' controls.
`<imagepath>plugin://script.artwork.downloader/multiimage/?image=$INFO[Container(9001).ListItem.Art(fanart)]&amp;&amp;image=$INFO[Container(9001).ListItem.Art(fanart1)]&amp;&amp;image=$INFO[Container(9001).ListItem.Art(fanart2)]&amp;&amp;image=$INFO[Container(9001).ListItem.Art(fanart3)]&amp;&amp;image=$INFO[Container(9001).ListItem.Art(fanart4)]&amp;&amp;image=$INFO[Container(9001).ListItem.Art(fanart5)]</imagepath>`
Repeat 'image', and the separator must be `&amp;&amp;` from skins.

Most of the code in default.py is moved to lib.main in an attempt to trim out a small delay in script startup. Compiled bytecode is saved and reused for imported modules, but not the script directly run, 'default.py'.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
made several comments. It's nice to see these changes done but please redo the commit history as it makes review difficult.
So please wait until i pushes my changes before doing a PR

**Comment by MartijnKaijser** [comment]
Additional i do not want this against Frodo branch. I will update master branch and it needs to be done against that one

**Comment by MartijnKaijser** [comment]
sorry for being a pain but i want the changes to be done in a logical order and easy to follow

**Comment by rmrector** [comment]
What's the status of the updates you wanted me to rebase on?

**Edit:** Removed unrelated notes.

**Comment by rmrector** [comment]
Your notes are spot on; the separate upgrade process isn't necessary and can easily be folded into the standard process, and on rebase I'll leave out other redundant stuff.

I've also got a handful of other changes I'd like to put together; putting season artwork into the database, sorting changes, episode fanart. They are smaller in scope than this one, so they shouldn't sprawl nearly so much. :smiley: I just need to know if you are interested, and what to rebase on.

**Comment by MartijnKaijser** [comment]
Whatever

**Pull request closed without merging**
