### PR TITLE
added missing polish strings.xml

### PR DESCRIPTION
**Pull request by cienislaw**
i'm still learning git and had some issue with repo. this is polish strings.xml.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Thanks :)

**Comment by cienislaw** [comment]
happy to help. i will try to watch and update on regular basis.

**Comment by MartijnKaijser** [comment]
String won't change that often got all in place that we need i think. Maybe just add one or two when i have worked out some ideas.

**Comment by cienislaw** [comment]
there are so many great scripts/plugins/skins which can benefit from polish translation. i will have more than enough to do. anyway, you can count on me on updating this project or translating new ones.

ps. i can't wait for working XBMC artwork pre-cache.

**Pull request merged**
